### ISSUE TITLE
Pledge Form

### ISSUE THREAD

**Issue by VenturaFranklin** [VenturaFranklin/thetatauCMT#211]
Add pledge form to the CMT

GanttStart: 2020-01-20
GanttDue: 2020-01-25

**Comment by VenturaFranklin** [comment]
Email confirmation to pledge.

**Comment by jimgaffneyTT** [comment]
Howdy - here are my notes on the pledge form.

-Under "pause and deliberate" can there be some text that instructs the pledges to please carefully read and answer each questions honestly?

-Can the default answer to each questions under "pause and deliberate" be blank instead of 'no.'

Otherwise, it's perfect.

**Comment by VenturaFranklin** [comment]
I made these changes, I just need the second email from you. @jimgaffneyTT

**Comment by VenturaFranklin** [comment]
Rolling welcome email, change to "complete part 1 of GreekLife.edu within 30 days of today"?

**Comment by VenturaFranklin** [comment]
Collect all past pledge forms into view like initiation process

**Comment by jimgaffneyTT** [comment]
I cannot for the life of me find the link to the live pledge form in the CMT; I'm 99% sure you told me it was up and runninng.
