### ISSUE TITLE
Resignation Workflow

### ISSUE THREAD

**Issue by VenturaFranklin** [VenturaFranklin/thetatauCMT#281]
@jimgaffneyTT can you provide details?

**Comment by jimgaffneyTT** [comment]
I have to check with Jamey on this one - I want to move this process entirely online (they wouldn't be uploading the form anymore, just filling in the information) since chapters might be remote.  I'll get back to you when I hear from him.

**Comment by jimgaffneyTT** [comment]
**Form 1 - Initial Report of Charges**

Text at top of form: 

> This form need only be submitted if your chapter is seeking to suspend or expel a member from the Fraternity.  If you are seeking other outcomes that do not include expulsion you do not need to notify the Central Office. Consult the Policies & Procedures Manual for specific instructions and rules governing discipline by Chapter.  

1. Name of accused [selected from dropdown of current chapter members]
2. Roll number of accused
3. Email address or accused
4. Charges (please specify which section of the PPM the member is accused of violating)
5. Did chapter officers try to resolve the problem through private discussion with the brother? [yes/no]
6. Was the chapter adviser involved in trying to resolve this problem? [yes/no]
7. Was a campus/faculty adviser involved in trying to resolve this problem? [yes/no]
8. Is a simple collections actions (for financial delinquency) better suited as a resolution to this issue? [yes/no]
	If yes, direct to collections referral form
9. Charges filed by majority vote at a chapter meeting on date: [date/must be today’s date or date in the past]
10. Accused notified of charges on date: [date]
11. Member notified via (check all that apply): [checkbox options: postal mail; email; text message; social media)
12. Trial scheduled for: [date, must be in the future]
13. Please attach a copy of the charging letter that was sent to the member. [file attachment]

_A copy of this form should be sent to all chapter officers, central.office, the RD and the ED and riskchair@thetatau.org (alias for Dan)_  

**Form 2 - Trial Report** -- _This form should be automatically emailed to the chapter regent on the day of the trial._

1. Did the trial take place as planned? [yes/no]
	If no: Why did the trial not take place? [dropdown: accused waived right to trial; rescheduled]
	If rescheduled: When will the trial be held? [date]
	_rescheduling the form should ‘snooze’ it until the new date and cause it to be resent the day of the new trial_

If answer to question 1 is yes, continue form:
2. Did the accused attend the trial and defend her/himself? [yes/no]
3. Was the accused found guilty of the charges by a ⅘ majority of the jury? [yes/no]
4. Did the chapter notify the member by mail/email of the results of the trial? [yes/no]
5. On what date was the member notified?
6. What was the punishment agreed to by the chapter? [dropdown: expelled; suspended.]
	If suspended: When will this member’s suspension end?
7. What other punishments, if any, were agreed to by the chapter?
8. If the member was suspended pending expulsion, did the chapter collect and receive the member’s badge, shingle and/or other Theta Tau property? [yes/no]
9. Please attach a copy of the minutes from the meeting where the trial was held.
10. Please attach a copy of the letter you sent to the member informing them of the outcome of the trial.

_A copy of this form should be sent to central.office, the ED, the RD and all chapter officers.  

It should generate a workflow item for the ED to “process” the form, with options to “accept and process expulsion/suspension,” “accept with no action” or “reject” the form.  If rejected, form 2 should be reopened so that the chapter can edit it again.__

_If accepted with no action, generate PDF’s of the two forms and email to CO for filing, complete workflow._

_If accepted for processing of expulsion/suspension, a form letter should be generated (I’ll email that to you separately) and it should be emailed to the member in question, Cc’ing central.office, riskchair@, ED, RD, chapter officers_


**Form 3 -- Send to EC**
__Form 3 should show up as a task 45 days after the email above is sent and be assigned to ED.  It should include a download option for forms 1 & 2 as well as all of the attachments and the form-letter form 2.

I should also have the option to upload any attachments I’ve received from the accused.

Once downloaded I should be able to click “sent to EC.”_

**Form 4 -- Outcome of EC**
_This form should be assigned to ED.  Option will be “Outcome approved by EC” or “Outcome Rejected by EC”_

“Rejected” completes workflow.

“Approved” should generate a form letter (I’ll email that to you separately) and email it to the accused, CC’ing central.office, ED, riskchair@, RD and chapter officers.  Workflow complete.

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT any updates on the resignation process?

**Comment by jimgaffneyTT** [comment]
Thanks for the nudge on this.  Let's format it just like the premature alumnus process for now, where we still have them submit the PDF.
