### ISSUE TITLE
Pledge Form - salutation

### ISSUE THREAD

**Issue by jimgaffneyTT** [VenturaFranklin/thetatauCMT#307]
Can you add "M." as one of the possible salutations in the pledge form please?

**Comment by VenturaFranklin** [comment]
I'm assuming this is for gender binary reasons?
From the gender census: https://gendercensus.com/post/183832246805/gender-census-2019-the-full-report-worldwide

It seems like the options should be:
- No title at all - 33.0% (up 0.6%)
- Mx - 31.3% (down 1.3%)
- Mr - 8.7% (up 0.2%)
- Non-gendered prof/acad. - 5.5% (up 0.1%)
- Ms - 4.7% (down 1.0%)

So I am going to add the Mx and a None option.

**Comment by jimgaffneyTT** [comment]
Sorry for the delay on this, can you make it “M.” instead of “Mx?”  Abe tells me that Mx is a slur directed at Mexican folks in some southwestern communities.

**Comment by VenturaFranklin** [comment]
Is there a source for that? I live in Arizona, I've never heard of Mx as a slur and Googling it I find nothing, literally nothing.

On the other side, M. is frowned on because it is too masculine or an abbreviation for monsieur which defeats the purpose as a non binary alternative.

If you still don't want Mx, we can just have the None option.

**Comment by jimgaffneyTT** [comment]
Mx being a slur is Abe and I’m choosing not to fight over it.  I’m less worries about M. being short for a salutation in French.  So let’s put M. in there and insert a “prefer not to answer” option.  Thoughts?
