### ISSUE TITLE
Conv Delegate Reporting

### ISSUE THREAD

**Issue by jimgaffneyTT** [VenturaFranklin/thetatauCMT#480]
Hey Frank,

Can you wipe out all of the chapter delegate information from the 2020 convention, relabel everything for the 2021 convention and report back when it's ready?  We want to launch on March 8.

Thanks! - J

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT This is already done. I do my best to never hard code dates, so there is no 2020 convention. ie. "forthcoming Convention" instead of something else. The system is actually setup to have a convention every term if we wanted to! Natoffs can see a list of completed forms here: https://cmt.thetatau.org/forms/convention-list

I don't think it makes sense to move the current delegates over to 2021. The chapter should elect new delegates. Also, no need to delete the current submissions as the filter for 2021 excludes them already.
